project_crm_root/course_app/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.delete, name='delete'),
    path('edit/<int:new_id>', views.edit, name='edit'),
]

project_crm_root/newcourse_app/urls.py
from django.urls import path
from . import views


# set a name for app
app_name = 'course_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('course/', views.course_add, name='course'),
    path('list/', views.list_course, name='list'),

]

project_crm_root/project_crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('course_app.urls')),
    path('new/', include('newcourse_app.urls')),
]

project_crm_root/course_app/models.py
from django.db import models


# Create your models here.
class CouseModel(models.Model):
    coursename = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.coursename

project_crm_root/newcourse_app/models.py
from django.db import models

# Create your models here.

project_crm_root/course_app/views.py
from django.shortcuts import render, HttpResponseRedirect
from .course_form import CourseForm
from .models import CouseModel
from django.urls import reverse


# Create your views here.

def index(request):
    # create isntance of form class
    form1 = CourseForm()
    courses = CouseModel.objects.all()

    # check whether request method is post
    if request.method == 'POST':
        # if, ok later create an instance of that submitted form. ie form posted to server
        form = CourseForm(request.POST)

        # validate data submitted in form
        if form.is_valid():
            # later save that form object to db.
            form.save(commit=True)

            # if all ok then return that template rendered in index view.
            return index(request)
    else:
        print('Error')

    # pass both the form object and courses query in a dictionary, then only both shown in same page
    return render(request, 'course_app/index.html', {'myform': form1, 'objs': courses})


def delete(request, course_id):
    course = CouseModel.objects.filter(id=course_id)
    course.delete()
    return index(request)


def edit(request, new_id):
    cours = CouseModel.objects.filter(id=new_id).first()
    # Create a form to edit an existing data, but use
    # POST data to populate the form.
    form2 = CourseForm(request.POST, instance=cours)
    if form2.is_valid():
        form2.save(commit=True)
        # to redirect to the index page after saving to db
        return HttpResponseRedirect(reverse('myapp:index'))
    return render(request, 'course_app/edit.html', {'newform': form2})

project_crm_root/newcourse_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'newcourse_app/index.html')


def course_add(request):
    return render(request, 'newcourse_app/add_course.html')


def list_course(request):
    return render(request, 'newcourse_app/list_course.html')

project_crm_root/templates/course_app/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <form action="#" method="post">
            {% csrf_token %}
            {{newform.as_p}}
            <button type="submit" class="btn btn-primary">save</button>
           <!-- <input type="text" name="" id="" value={{coursename}}>  -->
        </form>
        <!-- <div class="mt-3">
            <a href="{% url 'myapp:index' %}">add course</a>
        </div> -->
        
    </div>
</body>
</html>

project_crm_root/templates/course_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
    <div class="container">

        <form method="post" class="mt-5 pt-5">
            {% csrf_token %}
            {{myform.as_p}}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>


        <div>
            {% if objs %}
                <table>
                        <tbody>
                    {% for each in objs %}
                       <tr>
                            <td>{{each.coursename}}</td>
                            <td><a href="{% url 'myapp:delete' each.id %}" class="btn btn-danger">delete</a></td>
                            <td><a href="{% url 'myapp:edit' each.id %}" class="btn btn-success">edit</a></td>
                       </tr>
                    {% endfor %}                    
                        </tbody>
                </table>
            {% endif %}
        </div>
    </div>

</body>
</html>

project_crm_root/templates/newcourse_app/add_course.html
<!DOCTYPE html>

{% extends 'newcourse_app/base.html' %}

{% block body_block %}


<h1>Add Course here</h1>






{% endblock %}

project_crm_root/templates/newcourse_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-3">
        <div class="container">
            <a class="navbar-brand" href="#">CourseApp</a>
              <button class="navbar-toggler" data-toggle="collapse" data-target="#navlinks">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navlinks">
            <ul class="navbar-nav">
                <li class="nav-item mr-3">
                <!-- v refer to template rendered in index view -->
                    <!-- course_app is the appname set in urls.py -->
                    <a class="nav-link"href="{% url 'course_app:index' %}">Home</a>
                </li>
                <li class="nav-item mr-3">
                      <!-- v refer to template rendered in course view-->
                    <a class="nav-link" href="{% url 'course_app:course' %}">Add Course</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'course_app:list' %}">Courses</a>
                </li>

            </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body_block%}


        {% endblock %}

    </div>






    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>

</body>
</html>

project_crm_root/templates/newcourse_app/index.html
<!DOCTYPE html>

{% extends 'newcourse_app/base.html' %}
    {% block body_block %}


    <h1>Welcome</h1>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>








    {% endblock %}

project_crm_root/templates/newcourse_app/list_course.html
<!DOCTYPE html>

{% extends 'newcourse_app/base.html' %}

{% block body_block %}




    <h1>List Courses</h1>






{% endblock %}